### ISSUE TITLE
v3.0.3 crashes server when a player dies

### ISSUE THREAD

**Issue by colemy** [TwelveIterations/HardcoreRevival#18]
### server log

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/26/19 8:07 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.GameRules.func_82766_b(Ljava/lang/String;)Z
	at net.blay09.mods.hardcorerevival.handler.DeathHandler.onPlayerDeath(DeathHandler.java:56) ~[?:3.0.3] {}
	at net.minecraftforge.eventbus.ASMEventHandler_16_DeathHandler_onPlayerDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:341) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:439) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:969) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:829) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:559) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_180430_e(LivingEntity.java:1252) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.PlayerEntity.func_180430_e(PlayerEntity.java:1538) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.block.Block.func_180658_a(Block.java:675) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_184231_a(Entity.java:907) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_184231_a(LivingEntity.java:252) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71122_b(ServerPlayerEntity.java:791) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:760) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:126) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:57) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:123) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:663) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1437733400 bytes (1371 MB) / 3334995968 bytes (3180 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -Xmx6G -Xms2G
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 2; [ServerPlayerEntity['cpm9'/22, l='kamsooner', x=61.60, y=68.00, z=-527.91]]
	Data Packs: mod:waddles, mod:tramplestopper, mod:reap, mod:ping, mod:hardcorerevival, mod:gamemodeoverhaul, mod:elevatorid, mod:dde, mod:biomeinfo, mod:morpheus, mod:voxelmap, mod:jei, mod:worldedit, mod:forge, vanilla
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

### client log
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/26/19 8:12 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.world.GameRules.func_82766_b(Ljava/lang/String;)Z
	at net.blay09.mods.hardcorerevival.handler.DeathHandler.onPlayerDeath(DeathHandler.java:56) ~[?:3.0.3] {}
	at net.minecraftforge.eventbus.ASMEventHandler_27_DeathHandler_onPlayerDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.1-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:341) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70645_a(ServerPlayerEntity.java:439) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:969) ~[?:?] {}
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:559) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_180430_e(LivingEntity.java:1252) ~[?:?] {}
	at net.minecraft.entity.player.PlayerEntity.func_180430_e(PlayerEntity.java:1538) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.block.Block.func_180658_a(Block.java:675) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_184231_a(Entity.java:907) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_184231_a(LivingEntity.java:252) ~[?:?] {}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71122_b(ServerPlayerEntity.java:791) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:760) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:126) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:57) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:15) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:135) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:114) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:683) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:677) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:99) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:662) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3134784688 bytes (2989 MB) / 4194304000 bytes (4000 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 8; [ServerPlayerEntity['cpm9'/217, l='hcr test', x=275.94, y=72.00, z=15.07]]
	Data Packs: vanilla, mod:worldedit, mod:waddles, mod:voxelmap, mod:tramplestopper, mod:reap, mod:ping, mod:morpheus, mod:jei, mod:hardcorerevival, mod:gamemodeoverhaul, mod:forge, mod:elevatorid, mod:dde, mod:biomeinfo
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by BlayTheNinth** [comment]
The 1.14.2 version is not compatible with Minecraft 1.14.3. A port for Minecraft 1.14.3 has been released.
